### PR TITLE
feat: Allow partial execution of network

### PR DESCRIPTION
**Pull request by retraigo**
This PR adds the ability to execute a partial sequence of the network. This can be useful when designing models such as Autoencoders and GANs.

- [x] Allow partial execution of the network.
- [x] Add proper error handling for misconfiguration during partial execution (out-of-bound slicing, etc),
- [x] Write an example showcasing how to execute the network partially (Autoencoders?)

And...
- [x] Additionally added the ability to predict multiple input points in a single `net.predict()` call.

This is a breaking change for the `predict()` method. The following things are broken:
- Existing Examples
- GPU backend
- WASM backend

EDIT:
- Rewrite every example to use new `predict()` format.
  - [x] xor (all) (edit: skipping `xor.ipynb` for now)
  - [x] linear
  - [x] multiple-linear
  - [x] binary
  - [x] multiclass
  - [x] text
  - [ ] filters
  - [x] run
  - [x] mnist-predict

### CODE REVIEW

**Comment by retraigo** [comment]
On the flip side, the last change I mentioned now requires rewriting every example to follow the new `predict()` format (eg. Using a tensor2D for XOR instead of tensor1D).

**Comment by retraigo** [comment]
I'm updating just the `predict` routine of the `mnist` example without disturbing the rest for now.

**Comment by retraigo** [comment]
The last commit fixes #38

**Review by load1n9 — APPROVED** [review]
LGTM

**Pull request merged**
